[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DualNumbers = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
FinancialMonteCarlo = "078f23cc-2637-5a1d-aba6-8a9ba9a6ff83"
HyperDualNumbers = "50ceba7f-c3ee-5a84-a6e8-3ad40456ec97"

[compat]
BenchmarkTools = "0.4, 0.5, 0.6, 0.7, 1"
DualNumbers = "0.5, 0.6"
FinancialMonteCarlo = "0.3, 0.4"
HyperDualNumbers = "2, 3, 4"
julia = "1"
