name = "FinancialFFT"
uuid = "ccc4acef-1676-4a84-946d-4093fe376f06"
authors = ["Nicola <nicola.scaramuzzino@yandex.com> and contributors"]
version = "0.1.5"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
AlternateVectors = "54ac12d0-05a3-433d-adfa-205158e8d514"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FinancialMonteCarlo = "078f23cc-2637-5a1d-aba6-8a9ba9a6ff83"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
Adapt = "3, 4"
AlternateVectors = "0.1, 0.2, 0.3, 0.4, 0.5"
ChainRulesCore = "1"
DataInterpolations = "4, 5, 6, 7, 8"
FFTW = "1"
FinancialMonteCarlo = "0.3"
Interpolations = "0.10.1, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16"
MuladdMacro = "0.2"
Requires = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
